spring:
  profiles:
    active: prod


  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.web: DEBUG
      org.springframework.security.authentication: DEBUG

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://db:5432/project_installer
    username: postgres
    password: Porfik10
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
