spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fastdoors
    username: postgres
    password: Porfik10
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect